import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className +" container"}>
        
        <div className="flex flex-row">
        <SideBar/>
              
          <div className="basis-3/4 m-2">
              {children}
          </div> 
        </div>
        </body>
    </html>
  )
}
