import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/sidebare/sidebar'
import SideBar2 from './components/sidebare/sidebar2'
import Navbar from './components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="flex">
          <SideBar/>
              
          <div className="flex-auto m-2">
              <Navbar/>
              <div className='m-5'>
                {children}
              </div>
          </div> 
        </div>
        </body>
    </html>
  )
}
